module.exports = [
  {
    'id': '110000',
    'province_name': '北京市',
    'city_list': [
      {
        'id': '110100',
        'province_id': '110000',
        'city_name': '北京',
        'city_code': '131',
        'city_pinyin_code': 'beijing',
      },
    ],
  },
  {
    'id': '120000',
    'province_name': '天津市',
    'city_list': [
      {
        'id': '120100',
        'province_id': '120000',
        'city_name': '天津',
        'city_code': '332',
        'city_pinyin_code': 'tianjin',
      },
    ],
  },
  {
    'id': '130000',
    'province_name': '河北省',
    'city_list': [
      {
        'id': '130100',
        'province_id': '130000',
        'city_name': '石家庄',
        'city_code': '150',
        'city_pinyin_code': 'shijiazhuang',
      },
      {
        'id': '130200',
        'province_id': '130000',
        'city_name': '唐山',
        'city_code': '265',
        'city_pinyin_code': 'tangshan',
      },
      {
        'id': '130300',
        'province_id': '130000',
        'city_name': '秦皇岛',
        'city_code': '148',
        'city_pinyin_code': 'qinhuangdao',
      },
      {
        'id': '130400',
        'province_id': '130000',
        'city_name': '邯郸',
        'city_code': '151',
        'city_pinyin_code': 'handan',
      },
      {
        'id': '130500',
        'province_id': '130000',
        'city_name': '邢台',
        'city_code': '266',
        'city_pinyin_code': 'xingtai',
      },
      {
        'id': '130600',
        'province_id': '130000',
        'city_name': '保定',
        'city_code': '307',
        'city_pinyin_code': 'baoding',
      },
      {
        'id': '130700',
        'province_id': '130000',
        'city_name': '张家口',
        'city_code': '264',
        'city_pinyin_code': 'zhangjiakou',
      },
      {
        'id': '130800',
        'province_id': '130000',
        'city_name': '承德',
        'city_code': '207',
        'city_pinyin_code': 'chengde',
      },
      {
        'id': '130900',
        'province_id': '130000',
        'city_name': '沧州',
        'city_code': '149',
        'city_pinyin_code': 'cangzhou',
      },
      {
        'id': '131000',
        'province_id': '130000',
        'city_name': '廊坊',
        'city_code': '191',
        'city_pinyin_code': 'langfang',
      },
      {
        'id': '131100',
        'province_id': '130000',
        'city_name': '衡水',
        'city_code': '208',
        'city_pinyin_code': 'hengshui',
      },
    ],
  },
  {
    'id': '140000',
    'province_name': '山西省',
    'city_list': [
      {
        'id': '140100',
        'province_id': '140000',
        'city_name': '太原',
        'city_code': '176',
        'city_pinyin_code': 'taiyuan',
      },
      {
        'id': '140200',
        'province_id': '140000',
        'city_name': '大同',
        'city_code': '355',
        'city_pinyin_code': 'datong',
      },
      {
        'id': '140300',
        'province_id': '140000',
        'city_name': '阳泉',
        'city_code': '357',
        'city_pinyin_code': 'yangquan',
      },
      {
        'id': '140400',
        'province_id': '140000',
        'city_name': '长治',
        'city_code': '356',
        'city_pinyin_code': 'zhangzhi',
      },
      {
        'id': '140500',
        'province_id': '140000',
        'city_name': '晋城',
        'city_code': '290',
        'city_pinyin_code': 'jincheng',
      },
      {
        'id': '140600',
        'province_id': '140000',
        'city_name': '朔州',
        'city_code': '237',
        'city_pinyin_code': 'shuozhou',
      },
      {
        'id': '140700',
        'province_id': '140000',
        'city_name': '晋中',
        'city_code': '238',
        'city_pinyin_code': 'jinzhong',
      },
      {
        'id': '140800',
        'province_id': '140000',
        'city_name': '运城',
        'city_code': '328',
        'city_pinyin_code': 'yuncheng',
      },
      {
        'id': '140900',
        'province_id': '140000',
        'city_name': '忻州',
        'city_code': '367',
        'city_pinyin_code': 'xinzhou',
      },
      {
        'id': '141000',
        'province_id': '140000',
        'city_name': '临汾',
        'city_code': '368',
        'city_pinyin_code': 'linfen',
      },
      {
        'id': '141100',
        'province_id': '140000',
        'city_name': '吕梁',
        'city_code': '327',
        'city_pinyin_code': 'lvliang',
      },
    ],
  },
  {
    'id': '150000',
    'province_name': '内蒙古自治区',
    'city_list': [
      {
        'id': '150100',
        'province_id': '150000',
        'city_name': '呼和浩特',
        'city_code': '321',
        'city_pinyin_code': 'huhehaote',
      },
      {
        'id': '150200',
        'province_id': '150000',
        'city_name': '包头',
        'city_code': '229',
        'city_pinyin_code': 'baotou',
      },
      {
        'id': '150300',
        'province_id': '150000',
        'city_name': '乌海',
        'city_code': '123',
        'city_pinyin_code': 'wuhai',
      },
      {
        'id': '150400',
        'province_id': '150000',
        'city_name': '赤峰',
        'city_code': '297',
        'city_pinyin_code': 'chifeng',
      },
      {
        'id': '150500',
        'province_id': '150000',
        'city_name': '通辽',
        'city_code': '64',
        'city_pinyin_code': 'tongliao',
      },
      {
        'id': '150600',
        'province_id': '150000',
        'city_name': '鄂尔多斯',
        'city_code': '283',
        'city_pinyin_code': 'eerduosi',
      },
      {
        'id': '150700',
        'province_id': '150000',
        'city_name': '呼伦贝尔',
        'city_code': '61',
        'city_pinyin_code': 'hulunbeier',
      },
      {
        'id': '150800',
        'province_id': '150000',
        'city_name': '巴彦淖尔',
        'city_code': '169',
        'city_pinyin_code': 'bayannaoer',
      },
      {
        'id': '150900',
        'province_id': '150000',
        'city_name': '乌兰察布',
        'city_code': '168',
        'city_pinyin_code': 'wulanchabu',
      },
      {
        'id': '152200',
        'province_id': '150000',
        'city_name': '兴安',
        'city_code': '62',
        'city_pinyin_code': 'xingan',
      },
      {
        'id': '152500',
        'province_id': '150000',
        'city_name': '锡林郭勒',
        'city_code': '63',
        'city_pinyin_code': 'xilinguole',
      },
      {
        'id': '152900',
        'province_id': '150000',
        'city_name': '阿拉善',
        'city_code': '230',
        'city_pinyin_code': 'alashan',
      },
    ],
  },
  {
    'id': '210000',
    'province_name': '辽宁省',
    'city_list': [
      {
        'id': '210100',
        'province_id': '210000',
        'city_name': '沈阳',
        'city_code': '58',
        'city_pinyin_code': 'shenyang',
      },
      {
        'id': '210200',
        'province_id': '210000',
        'city_name': '大连',
        'city_code': '167',
        'city_pinyin_code': 'dalian',
      },
      {
        'id': '210300',
        'province_id': '210000',
        'city_name': '鞍山',
        'city_code': '320',
        'city_pinyin_code': 'anshan',
      },
      {
        'id': '210400',
        'province_id': '210000',
        'city_name': '抚顺',
        'city_code': '184',
        'city_pinyin_code': 'fushun',
      },
      {
        'id': '210500',
        'province_id': '210000',
        'city_name': '本溪',
        'city_code': '227',
        'city_pinyin_code': 'benxi',
      },
      {
        'id': '210600',
        'province_id': '210000',
        'city_name': '丹东',
        'city_code': '282',
        'city_pinyin_code': 'dandong',
      },
      {
        'id': '210700',
        'province_id': '210000',
        'city_name': '锦州',
        'city_code': '166',
        'city_pinyin_code': 'jinzhou',
      },
      {
        'id': '210800',
        'province_id': '210000',
        'city_name': '营口',
        'city_code': '281',
        'city_pinyin_code': 'yingkou',
      },
      {
        'id': '210900',
        'province_id': '210000',
        'city_name': '阜新',
        'city_code': '59',
        'city_pinyin_code': 'fuxin',
      },
      {
        'id': '211000',
        'province_id': '210000',
        'city_name': '辽阳',
        'city_code': '351',
        'city_pinyin_code': 'liaoyang',
      },
      {
        'id': '211100',
        'province_id': '210000',
        'city_name': '盘锦',
        'city_code': '228',
        'city_pinyin_code': 'panjin',
      },
      {
        'id': '211200',
        'province_id': '210000',
        'city_name': '铁岭',
        'city_code': '60',
        'city_pinyin_code': 'tieling',
      },
      {
        'id': '211300',
        'province_id': '210000',
        'city_name': '朝阳',
        'city_code': '280',
        'city_pinyin_code': 'chaoyang',
      },
      {
        'id': '211400',
        'province_id': '210000',
        'city_name': '葫芦岛',
        'city_code': '319',
        'city_pinyin_code': 'huludao',
      },
    ],
  },
  {
    'id': '220000',
    'province_name': '吉林省',
    'city_list': [
      {
        'id': '220100',
        'province_id': '220000',
        'city_name': '长春',
        'city_code': '53',
        'city_pinyin_code': 'zhangchun',
      },
      {
        'id': '220200',
        'province_id': '220000',
        'city_name': '吉林',
        'city_code': '9',
        'city_pinyin_code': 'jilin',
      },
      {
        'id': '220300',
        'province_id': '220000',
        'city_name': '四平',
        'city_code': '56',
        'city_pinyin_code': 'siping',
      },
      {
        'id': '220400',
        'province_id': '220000',
        'city_name': '辽源',
        'city_code': '183',
        'city_pinyin_code': 'liaoyuan',
      },
      {
        'id': '220500',
        'province_id': '220000',
        'city_name': '通化',
        'city_code': '165',
        'city_pinyin_code': 'tonghua',
      },
      {
        'id': '220600',
        'province_id': '220000',
        'city_name': '白山',
        'city_code': '57',
        'city_pinyin_code': 'baishan',
      },
      {
        'id': '220700',
        'province_id': '220000',
        'city_name': '松原',
        'city_code': '52',
        'city_pinyin_code': 'songyuan',
      },
      {
        'id': '220800',
        'province_id': '220000',
        'city_name': '白城',
        'city_code': '51',
        'city_pinyin_code': 'baicheng',
      },
      {
        'id': '222400',
        'province_id': '220000',
        'city_name': '延边朝鲜族自治州',
        'city_code': '54',
        'city_pinyin_code': 'yanbianchaoxianzuzizhizhou',
      },
    ],
  },
  {
    'id': '230000',
    'province_name': '黑龙江省',
    'city_list': [
      {
        'id': '230100',
        'province_id': '230000',
        'city_name': '哈尔滨',
        'city_code': '48',
        'city_pinyin_code': 'haerbin',
      },
      {
        'id': '230200',
        'province_id': '230000',
        'city_name': '齐齐哈尔',
        'city_code': '41',
        'city_pinyin_code': 'qiqihaer',
      },
      {
        'id': '230300',
        'province_id': '230000',
        'city_name': '鸡西',
        'city_code': '46',
        'city_pinyin_code': 'jixi',
      },
      {
        'id': '230400',
        'province_id': '230000',
        'city_name': '鹤岗',
        'city_code': '43',
        'city_pinyin_code': 'hegang',
      },
      {
        'id': '230500',
        'province_id': '230000',
        'city_name': '双鸭山',
        'city_code': '45',
        'city_pinyin_code': 'shuangyashan',
      },
      {
        'id': '230600',
        'province_id': '230000',
        'city_name': '大庆',
        'city_code': '50',
        'city_pinyin_code': 'daqing',
      },
      {
        'id': '230700',
        'province_id': '230000',
        'city_name': '伊春',
        'city_code': '40',
        'city_pinyin_code': 'yichun',
      },
      {
        'id': '230800',
        'province_id': '230000',
        'city_name': '佳木斯',
        'city_code': '42',
        'city_pinyin_code': 'jiamusi',
      },
      {
        'id': '230900',
        'province_id': '230000',
        'city_name': '七台河',
        'city_code': '47',
        'city_pinyin_code': 'qitaihe',
      },
      {
        'id': '231000',
        'province_id': '230000',
        'city_name': '牡丹江',
        'city_code': '49',
        'city_pinyin_code': 'mudanjiang',
      },
      {
        'id': '231100',
        'province_id': '230000',
        'city_name': '黑河',
        'city_code': '39',
        'city_pinyin_code': 'heihe',
      },
      {
        'id': '231200',
        'province_id': '230000',
        'city_name': '绥化',
        'city_code': '44',
        'city_pinyin_code': 'suihua',
      },
      {
        'id': '232700',
        'province_id': '230000',
        'city_name': '大兴安岭地区',
        'city_code': '38',
        'city_pinyin_code': 'daxinganlingdiqu',
      },
    ],
  },
  {
    'id': '310000',
    'province_name': '上海市',
    'city_list': [
      {
        'id': '310100',
        'province_id': '310000',
        'city_name': '上海',
        'city_code': '289',
        'city_pinyin_code': 'shanghai',
      },
    ],
  },
  {
    'id': '320000',
    'province_name': '江苏省',
    'city_list': [
      {
        'id': '320100',
        'province_id': '320000',
        'city_name': '南京',
        'city_code': '315',
        'city_pinyin_code': 'nanjing',
      },
      {
        'id': '320200',
        'province_id': '320000',
        'city_name': '无锡',
        'city_code': '317',
        'city_pinyin_code': 'wuxi',
      },
      {
        'id': '320300',
        'province_id': '320000',
        'city_name': '徐州',
        'city_code': '316',
        'city_pinyin_code': 'xuzhou',
      },
      {
        'id': '320400',
        'province_id': '320000',
        'city_name': '常州',
        'city_code': '348',
        'city_pinyin_code': 'changzhou',
      },
      {
        'id': '320500',
        'province_id': '320000',
        'city_name': '苏州',
        'city_code': '224',
        'city_pinyin_code': 'suzhou',
      },
      {
        'id': '320600',
        'province_id': '320000',
        'city_name': '南通',
        'city_code': '161',
        'city_pinyin_code': 'nantong',
      },
      {
        'id': '320700',
        'province_id': '320000',
        'city_name': '连云港',
        'city_code': '347',
        'city_pinyin_code': 'lianyungang',
      },
      {
        'id': '320800',
        'province_id': '320000',
        'city_name': '淮安',
        'city_code': '162',
        'city_pinyin_code': 'huaian',
      },
      {
        'id': '320900',
        'province_id': '320000',
        'city_name': '盐城',
        'city_code': '223',
        'city_pinyin_code': 'yancheng',
      },
      {
        'id': '321000',
        'province_id': '320000',
        'city_name': '扬州',
        'city_code': '346',
        'city_pinyin_code': 'yangzhou',
      },
      {
        'id': '321100',
        'province_id': '320000',
        'city_name': '镇江',
        'city_code': '160',
        'city_pinyin_code': 'zhenjiang',
      },
      {
        'id': '321200',
        'province_id': '320000',
        'city_name': '泰州',
        'city_code': '276',
        'city_pinyin_code': 'taizhou',
      },
      {
        'id': '321300',
        'province_id': '320000',
        'city_name': '宿迁',
        'city_code': '277',
        'city_pinyin_code': 'suqian',
      },
    ],
  },
  {
    'id': '330000',
    'province_name': '浙江省',
    'city_list': [
      {
        'id': '330100',
        'province_id': '330000',
        'city_name': '杭州',
        'city_code': '179',
        'city_pinyin_code': 'hangzhou',
      },
      {
        'id': '330200',
        'province_id': '330000',
        'city_name': '宁波',
        'city_code': '180',
        'city_pinyin_code': 'ningbo',
      },
      {
        'id': '330300',
        'province_id': '330000',
        'city_name': '温州',
        'city_code': '178',
        'city_pinyin_code': 'wenzhou',
      },
      {
        'id': '330400',
        'province_id': '330000',
        'city_name': '嘉兴',
        'city_code': '334',
        'city_pinyin_code': 'jiaxing',
      },
      {
        'id': '330500',
        'province_id': '330000',
        'city_name': '湖州',
        'city_code': '294',
        'city_pinyin_code': 'huzhou',
      },
      {
        'id': '330600',
        'province_id': '330000',
        'city_name': '绍兴',
        'city_code': '293',
        'city_pinyin_code': 'shaoxing',
      },
      {
        'id': '330700',
        'province_id': '330000',
        'city_name': '金华',
        'city_code': '333',
        'city_pinyin_code': 'jinhua',
      },
      {
        'id': '330800',
        'province_id': '330000',
        'city_name': '衢州',
        'city_code': '243',
        'city_pinyin_code': 'quzhou',
      },
      {
        'id': '330900',
        'province_id': '330000',
        'city_name': '舟山',
        'city_code': '245',
        'city_pinyin_code': 'zhoushan',
      },
      {
        'id': '331000',
        'province_id': '330000',
        'city_name': '台州',
        'city_code': '244',
        'city_pinyin_code': 'taizhou',
      },
      {
        'id': '331100',
        'province_id': '330000',
        'city_name': '丽水',
        'city_code': '292',
        'city_pinyin_code': 'lishui',
      },
    ],
  },
  {
    'id': '340000',
    'province_name': '安徽省',
    'city_list': [
      {
        'id': '340100',
        'province_id': '340000',
        'city_name': '合肥',
        'city_code': '127',
        'city_pinyin_code': 'hefei',
      },
      {
        'id': '340200',
        'province_id': '340000',
        'city_name': '芜湖',
        'city_code': '129',
        'city_pinyin_code': 'wuhu',
      },
      {
        'id': '340300',
        'province_id': '340000',
        'city_name': '蚌埠',
        'city_code': '126',
        'city_pinyin_code': 'bangbu',
      },
      {
        'id': '340400',
        'province_id': '340000',
        'city_name': '淮南',
        'city_code': '250',
        'city_pinyin_code': 'huainan',
      },
      {
        'id': '340500',
        'province_id': '340000',
        'city_name': '马鞍山',
        'city_code': '358',
        'city_pinyin_code': 'maanshan',
      },
      {
        'id': '340600',
        'province_id': '340000',
        'city_name': '淮北',
        'city_code': '253',
        'city_pinyin_code': 'huaibei',
      },
      {
        'id': '340700',
        'province_id': '340000',
        'city_name': '铜陵',
        'city_code': '337',
        'city_pinyin_code': 'tongling',
      },
      {
        'id': '340800',
        'province_id': '340000',
        'city_name': '安庆',
        'city_code': '130',
        'city_pinyin_code': 'anqing',
      },
      {
        'id': '341000',
        'province_id': '340000',
        'city_name': '黄山',
        'city_code': '252',
        'city_pinyin_code': 'huangshan',
      },
      {
        'id': '341100',
        'province_id': '340000',
        'city_name': '滁州',
        'city_code': '189',
        'city_pinyin_code': 'chuzhou',
      },
      {
        'id': '341200',
        'province_id': '340000',
        'city_name': '阜阳',
        'city_code': '128',
        'city_pinyin_code': 'fuyang',
      },
      {
        'id': '341300',
        'province_id': '340000',
        'city_name': '宿州',
        'city_code': '370',
        'city_pinyin_code': 'suzhou',
      },
      {
        'id': '341400',
        'province_id': '340000',
        'city_name': '巢湖',
        'city_code': '251',
        'city_pinyin_code': 'chaohu',
      },
      {
        'id': '341500',
        'province_id': '340000',
        'city_name': '六安',
        'city_code': '298',
        'city_pinyin_code': 'luan',
      },
      {
        'id': '341600',
        'province_id': '340000',
        'city_name': '亳州',
        'city_code': '188',
        'city_pinyin_code': 'bozhou',
      },
      {
        'id': '341700',
        'province_id': '340000',
        'city_name': '池州',
        'city_code': '299',
        'city_pinyin_code': 'chizhou',
      },
      {
        'id': '341800',
        'province_id': '340000',
        'city_name': '宣城',
        'city_code': '190',
        'city_pinyin_code': 'xuancheng',
      },
    ],
  },
  {
    'id': '350000',
    'province_name': '福建省',
    'city_list': [
      {
        'id': '350100',
        'province_id': '350000',
        'city_name': '福州',
        'city_code': '300',
        'city_pinyin_code': 'fuzhou',
      },
      {
        'id': '350200',
        'province_id': '350000',
        'city_name': '厦门',
        'city_code': '194',
        'city_pinyin_code': 'shamen',
      },
      {
        'id': '350300',
        'province_id': '350000',
        'city_name': '莆田',
        'city_code': '195',
        'city_pinyin_code': 'putian',
      },
      {
        'id': '350400',
        'province_id': '350000',
        'city_name': '三明',
        'city_code': '254',
        'city_pinyin_code': 'sanming',
      },
      {
        'id': '350500',
        'province_id': '350000',
        'city_name': '泉州',
        'city_code': '134',
        'city_pinyin_code': 'quanzhou',
      },
      {
        'id': '350600',
        'province_id': '350000',
        'city_name': '漳州',
        'city_code': '255',
        'city_pinyin_code': 'zhangzhou',
      },
      {
        'id': '350700',
        'province_id': '350000',
        'city_name': '南平',
        'city_code': '133',
        'city_pinyin_code': 'nanping',
      },
      {
        'id': '350800',
        'province_id': '350000',
        'city_name': '龙岩',
        'city_code': '193',
        'city_pinyin_code': 'longyan',
      },
      {
        'id': '350900',
        'province_id': '350000',
        'city_name': '宁德',
        'city_code': '192',
        'city_pinyin_code': 'ningde',
      },
    ],
  },
  {
    'id': '360000',
    'province_name': '江西省',
    'city_list': [
      {
        'id': '360100',
        'province_id': '360000',
        'city_name': '南昌',
        'city_code': '163',
        'city_pinyin_code': 'nanchang',
      },
      {
        'id': '360200',
        'province_id': '360000',
        'city_name': '景德镇',
        'city_code': '225',
        'city_pinyin_code': 'jingdezhen',
      },
      {
        'id': '360300',
        'province_id': '360000',
        'city_name': '萍乡',
        'city_code': '350',
        'city_pinyin_code': 'pingxiang',
      },
      {
        'id': '360400',
        'province_id': '360000',
        'city_name': '九江',
        'city_code': '349',
        'city_pinyin_code': 'jiujiang',
      },
      {
        'id': '360500',
        'province_id': '360000',
        'city_name': '新余',
        'city_code': '164',
        'city_pinyin_code': 'xinyu',
      },
      {
        'id': '360600',
        'province_id': '360000',
        'city_name': '鹰潭',
        'city_code': '279',
        'city_pinyin_code': 'yingtan',
      },
      {
        'id': '360700',
        'province_id': '360000',
        'city_name': '赣州',
        'city_code': '365',
        'city_pinyin_code': 'ganzhou',
      },
      {
        'id': '360800',
        'province_id': '360000',
        'city_name': '吉安',
        'city_code': '318',
        'city_pinyin_code': 'jian',
      },
      {
        'id': '360900',
        'province_id': '360000',
        'city_name': '宜春',
        'city_code': '278',
        'city_pinyin_code': 'yichun',
      },
      {
        'id': '361000',
        'province_id': '360000',
        'city_name': '抚州',
        'city_code': '226',
        'city_pinyin_code': 'fuzhou',
      },
      {
        'id': '361100',
        'province_id': '360000',
        'city_name': '上饶',
        'city_code': '364',
        'city_pinyin_code': 'shangrao',
      },
    ],
  },
  {
    'id': '370000',
    'province_name': '山东省',
    'city_list': [
      {
        'id': '370100',
        'province_id': '370000',
        'city_name': '济南',
        'city_code': '288',
        'city_pinyin_code': 'jinan',
      },
      {
        'id': '370200',
        'province_id': '370000',
        'city_name': '青岛',
        'city_code': '236',
        'city_pinyin_code': 'qingdao',
      },
      {
        'id': '370300',
        'province_id': '370000',
        'city_name': '淄博',
        'city_code': '354',
        'city_pinyin_code': 'zibo',
      },
      {
        'id': '370400',
        'province_id': '370000',
        'city_name': '枣庄',
        'city_code': '172',
        'city_pinyin_code': 'zaozhuang',
      },
      {
        'id': '370500',
        'province_id': '370000',
        'city_name': '东营',
        'city_code': '174',
        'city_pinyin_code': 'dongying',
      },
      {
        'id': '370600',
        'province_id': '370000',
        'city_name': '烟台',
        'city_code': '326',
        'city_pinyin_code': 'yantai',
      },
      {
        'id': '370700',
        'province_id': '370000',
        'city_name': '潍坊',
        'city_code': '287',
        'city_pinyin_code': 'weifang',
      },
      {
        'id': '370800',
        'province_id': '370000',
        'city_name': '济宁',
        'city_code': '286',
        'city_pinyin_code': 'jining',
      },
      {
        'id': '370900',
        'province_id': '370000',
        'city_name': '泰安',
        'city_code': '325',
        'city_pinyin_code': 'taian',
      },
      {
        'id': '371000',
        'province_id': '370000',
        'city_name': '威海',
        'city_code': '175',
        'city_pinyin_code': 'weihai',
      },
      {
        'id': '371100',
        'province_id': '370000',
        'city_name': '日照',
        'city_code': '173',
        'city_pinyin_code': 'rizhao',
      },
      {
        'id': '371200',
        'province_id': '370000',
        'city_name': '莱芜',
        'city_code': '124',
        'city_pinyin_code': 'laiwu',
      },
      {
        'id': '371300',
        'province_id': '370000',
        'city_name': '临沂',
        'city_code': '234',
        'city_pinyin_code': 'linyi',
      },
      {
        'id': '371400',
        'province_id': '370000',
        'city_name': '德州',
        'city_code': '372',
        'city_pinyin_code': 'dezhou',
      },
      {
        'id': '371500',
        'province_id': '370000',
        'city_name': '聊城',
        'city_code': '366',
        'city_pinyin_code': 'liaocheng',
      },
      {
        'id': '371600',
        'province_id': '370000',
        'city_name': '滨州',
        'city_code': '235',
        'city_pinyin_code': 'binzhou',
      },
      {
        'id': '371700',
        'province_id': '370000',
        'city_name': '荷泽',
        'city_code': '0',
        'city_pinyin_code': 'heze',
      },
    ],
  },
  {
    'id': '410000',
    'province_name': '河南省',
    'city_list': [
      {
        'id': '410100',
        'province_id': '410000',
        'city_name': '郑州',
        'city_code': '268',
        'city_pinyin_code': 'zhengzhou',
      },
      {
        'id': '410200',
        'province_id': '410000',
        'city_name': '开封',
        'city_code': '210',
        'city_pinyin_code': 'kaifeng',
      },
      {
        'id': '410300',
        'province_id': '410000',
        'city_name': '洛阳',
        'city_code': '153',
        'city_pinyin_code': 'luoyang',
      },
      {
        'id': '410400',
        'province_id': '410000',
        'city_name': '平顶山',
        'city_code': '213',
        'city_pinyin_code': 'pingdingshan',
      },
      {
        'id': '410500',
        'province_id': '410000',
        'city_name': '安阳',
        'city_code': '267',
        'city_pinyin_code': 'anyang',
      },
      {
        'id': '410600',
        'province_id': '410000',
        'city_name': '鹤壁',
        'city_code': '215',
        'city_pinyin_code': 'hebi',
      },
      {
        'id': '410700',
        'province_id': '410000',
        'city_name': '新乡',
        'city_code': '152',
        'city_pinyin_code': 'xinxiang',
      },
      {
        'id': '410800',
        'province_id': '410000',
        'city_name': '焦作',
        'city_code': '211',
        'city_pinyin_code': 'jiaozuo',
      },
      {
        'id': '410900',
        'province_id': '410000',
        'city_name': '濮阳',
        'city_code': '209',
        'city_pinyin_code': 'puyang',
      },
      {
        'id': '411000',
        'province_id': '410000',
        'city_name': '许昌',
        'city_code': '155',
        'city_pinyin_code': 'xuchang',
      },
      {
        'id': '411100',
        'province_id': '410000',
        'city_name': '漯河',
        'city_code': '344',
        'city_pinyin_code': 'luohe',
      },
      {
        'id': '411200',
        'province_id': '410000',
        'city_name': '三门峡',
        'city_code': '212',
        'city_pinyin_code': 'sanmenxia',
      },
      {
        'id': '411300',
        'province_id': '410000',
        'city_name': '南阳',
        'city_code': '309',
        'city_pinyin_code': 'nanyang',
      },
      {
        'id': '411400',
        'province_id': '410000',
        'city_name': '商丘',
        'city_code': '154',
        'city_pinyin_code': 'shangqiu',
      },
      {
        'id': '411500',
        'province_id': '410000',
        'city_name': '信阳',
        'city_code': '214',
        'city_pinyin_code': 'xinyang',
      },
      {
        'id': '411600',
        'province_id': '410000',
        'city_name': '周口',
        'city_code': '308',
        'city_pinyin_code': 'zhoukou',
      },
      {
        'id': '411700',
        'province_id': '410000',
        'city_name': '驻马店',
        'city_code': '269',
        'city_pinyin_code': 'zhumadian',
      },
    ],
  },
  {
    'id': '420000',
    'province_name': '湖北省',
    'city_list': [
      {
        'id': '420100',
        'province_id': '420000',
        'city_name': '武汉',
        'city_code': '218',
        'city_pinyin_code': 'wuhan',
      },
      {
        'id': '420200',
        'province_id': '420000',
        'city_name': '黄石',
        'city_code': '311',
        'city_pinyin_code': 'huangshi',
      },
      {
        'id': '420300',
        'province_id': '420000',
        'city_name': '十堰',
        'city_code': '216',
        'city_pinyin_code': 'shiyan',
      },
      {
        'id': '420500',
        'province_id': '420000',
        'city_name': '宜昌',
        'city_code': '270',
        'city_pinyin_code': 'yichang',
      },
      {
        'id': '420600',
        'province_id': '420000',
        'city_name': '襄樊',
        'city_code': '0',
        'city_pinyin_code': 'xiangfan',
      },
      {
        'id': '420700',
        'province_id': '420000',
        'city_name': '鄂州',
        'city_code': '122',
        'city_pinyin_code': 'ezhou',
      },
      {
        'id': '420800',
        'province_id': '420000',
        'city_name': '荆门',
        'city_code': '217',
        'city_pinyin_code': 'jingmen',
      },
      {
        'id': '420900',
        'province_id': '420000',
        'city_name': '孝感',
        'city_code': '310',
        'city_pinyin_code': 'xiaogan',
      },
      {
        'id': '421000',
        'province_id': '420000',
        'city_name': '荆州',
        'city_code': '157',
        'city_pinyin_code': 'jingzhou',
      },
      {
        'id': '421100',
        'province_id': '420000',
        'city_name': '黄冈',
        'city_code': '271',
        'city_pinyin_code': 'huanggang',
      },
      {
        'id': '421200',
        'province_id': '420000',
        'city_name': '咸宁',
        'city_code': '362',
        'city_pinyin_code': 'xianning',
      },
      {
        'id': '421300',
        'province_id': '420000',
        'city_name': '随州',
        'city_code': '371',
        'city_pinyin_code': 'suizhou',
      },
      {
        'id': '422800',
        'province_id': '420000',
        'city_name': '恩施土家族苗族自治州',
        'city_code': '373',
        'city_pinyin_code': 'enshitujiazumiaozuzizhizhou',
      },
    ],
  },
  {
    'id': '430000',
    'province_name': '湖南省',
    'city_list': [
      {
        'id': '430100',
        'province_id': '430000',
        'city_name': '长沙',
        'city_code': '158',
        'city_pinyin_code': 'zhangsha',
      },
      {
        'id': '430200',
        'province_id': '430000',
        'city_name': '株洲',
        'city_code': '222',
        'city_pinyin_code': 'zhuzhou',
      },
      {
        'id': '430300',
        'province_id': '430000',
        'city_name': '湘潭',
        'city_code': '313',
        'city_pinyin_code': 'xiangtan',
      },
      {
        'id': '430400',
        'province_id': '430000',
        'city_name': '衡阳',
        'city_code': '159',
        'city_pinyin_code': 'hengyang',
      },
      {
        'id': '430500',
        'province_id': '430000',
        'city_name': '邵阳',
        'city_code': '273',
        'city_pinyin_code': 'shaoyang',
      },
      {
        'id': '430600',
        'province_id': '430000',
        'city_name': '岳阳',
        'city_code': '220',
        'city_pinyin_code': 'yueyang',
      },
      {
        'id': '430700',
        'province_id': '430000',
        'city_name': '常德',
        'city_code': '219',
        'city_pinyin_code': 'changde',
      },
      {
        'id': '430800',
        'province_id': '430000',
        'city_name': '张家界',
        'city_code': '312',
        'city_pinyin_code': 'zhangjiajie',
      },
      {
        'id': '430900',
        'province_id': '430000',
        'city_name': '益阳',
        'city_code': '272',
        'city_pinyin_code': 'yiyang',
      },
      {
        'id': '431000',
        'province_id': '430000',
        'city_name': '郴州',
        'city_code': '275',
        'city_pinyin_code': 'chenzhou',
      },
      {
        'id': '431100',
        'province_id': '430000',
        'city_name': '永州',
        'city_code': '314',
        'city_pinyin_code': 'yongzhou',
      },
      {
        'id': '431200',
        'province_id': '430000',
        'city_name': '怀化',
        'city_code': '363',
        'city_pinyin_code': 'huaihua',
      },
      {
        'id': '431300',
        'province_id': '430000',
        'city_name': '娄底',
        'city_code': '221',
        'city_pinyin_code': 'loudi',
      },
      {
        'id': '433100',
        'province_id': '430000',
        'city_name': '湘西土家族苗族自治州',
        'city_code': '274',
        'city_pinyin_code': 'xiangxitujiazumiaozuzizhizhou',
      },
    ],
  },
  {
    'id': '440000',
    'province_name': '广东省',
    'city_list': [
      {
        'id': '440100',
        'province_id': '440000',
        'city_name': '广州',
        'city_code': '257',
        'city_pinyin_code': 'guangzhou',
      },
      {
        'id': '440200',
        'province_id': '440000',
        'city_name': '韶关',
        'city_code': '137',
        'city_pinyin_code': 'shaoguan',
      },
      {
        'id': '440300',
        'province_id': '440000',
        'city_name': '深圳',
        'city_code': '340',
        'city_pinyin_code': 'shenzhen',
      },
      {
        'id': '440400',
        'province_id': '440000',
        'city_name': '珠海',
        'city_code': '140',
        'city_pinyin_code': 'zhuhai',
      },
      {
        'id': '440500',
        'province_id': '440000',
        'city_name': '汕头',
        'city_code': '303',
        'city_pinyin_code': 'shantou',
      },
      {
        'id': '440600',
        'province_id': '440000',
        'city_name': '佛山',
        'city_code': '138',
        'city_pinyin_code': 'foshan',
      },
      {
        'id': '440700',
        'province_id': '440000',
        'city_name': '江门',
        'city_code': '302',
        'city_pinyin_code': 'jiangmen',
      },
      {
        'id': '440800',
        'province_id': '440000',
        'city_name': '湛江',
        'city_code': '198',
        'city_pinyin_code': 'zhanjiang',
      },
      {
        'id': '440900',
        'province_id': '440000',
        'city_name': '茂名',
        'city_code': '139',
        'city_pinyin_code': 'maoming',
      },
      {
        'id': '441200',
        'province_id': '440000',
        'city_name': '肇庆',
        'city_code': '338',
        'city_pinyin_code': 'zhaoqing',
      },
      {
        'id': '441300',
        'province_id': '440000',
        'city_name': '惠州',
        'city_code': '301',
        'city_pinyin_code': 'huizhou',
      },
      {
        'id': '441400',
        'province_id': '440000',
        'city_name': '梅州',
        'city_code': '141',
        'city_pinyin_code': 'meizhou',
      },
      {
        'id': '441500',
        'province_id': '440000',
        'city_name': '汕尾',
        'city_code': '339',
        'city_pinyin_code': 'shanwei',
      },
      {
        'id': '441600',
        'province_id': '440000',
        'city_name': '河源',
        'city_code': '200',
        'city_pinyin_code': 'heyuan',
      },
      {
        'id': '441700',
        'province_id': '440000',
        'city_name': '阳江',
        'city_code': '199',
        'city_pinyin_code': 'yangjiang',
      },
      {
        'id': '441800',
        'province_id': '440000',
        'city_name': '清远',
        'city_code': '197',
        'city_pinyin_code': 'qingyuan',
      },
      {
        'id': '441900',
        'province_id': '440000',
        'city_name': '东莞',
        'city_code': '119',
        'city_pinyin_code': 'dongguan',
      },
      {
        'id': '442000',
        'province_id': '440000',
        'city_name': '中山',
        'city_code': '187',
        'city_pinyin_code': 'zhongshan',
      },
      {
        'id': '445100',
        'province_id': '440000',
        'city_name': '潮州',
        'city_code': '201',
        'city_pinyin_code': 'chaozhou',
      },
      {
        'id': '445200',
        'province_id': '440000',
        'city_name': '揭阳',
        'city_code': '259',
        'city_pinyin_code': 'jieyang',
      },
      {
        'id': '445300',
        'province_id': '440000',
        'city_name': '云浮',
        'city_code': '258',
        'city_pinyin_code': 'yunfu',
      },
    ],
  },
  {
    'id': '450000',
    'province_name': '广西壮族自治区',
    'city_list': [
      {
        'id': '450100',
        'province_id': '450000',
        'city_name': '南宁',
        'city_code': '261',
        'city_pinyin_code': 'nanning',
      },
      {
        'id': '450200',
        'province_id': '450000',
        'city_name': '柳州',
        'city_code': '305',
        'city_pinyin_code': 'liuzhou',
      },
      {
        'id': '450300',
        'province_id': '450000',
        'city_name': '桂林',
        'city_code': '142',
        'city_pinyin_code': 'guilin',
      },
      {
        'id': '450400',
        'province_id': '450000',
        'city_name': '梧州',
        'city_code': '304',
        'city_pinyin_code': 'wuzhou',
      },
      {
        'id': '450500',
        'province_id': '450000',
        'city_name': '北海',
        'city_code': '295',
        'city_pinyin_code': 'beihai',
      },
      {
        'id': '450600',
        'province_id': '450000',
        'city_name': '防城港',
        'city_code': '204',
        'city_pinyin_code': 'fangchenggang',
      },
      {
        'id': '450700',
        'province_id': '450000',
        'city_name': '钦州',
        'city_code': '145',
        'city_pinyin_code': 'qinzhou',
      },
      {
        'id': '450800',
        'province_id': '450000',
        'city_name': '贵港',
        'city_code': '341',
        'city_pinyin_code': 'guigang',
      },
      {
        'id': '450900',
        'province_id': '450000',
        'city_name': '玉林',
        'city_code': '361',
        'city_pinyin_code': 'yulin',
      },
      {
        'id': '451000',
        'province_id': '450000',
        'city_name': '百色',
        'city_code': '203',
        'city_pinyin_code': 'baise',
      },
      {
        'id': '451100',
        'province_id': '450000',
        'city_name': '贺州',
        'city_code': '260',
        'city_pinyin_code': 'hezhou',
      },
      {
        'id': '451200',
        'province_id': '450000',
        'city_name': '河池',
        'city_code': '143',
        'city_pinyin_code': 'hechi',
      },
      {
        'id': '451300',
        'province_id': '450000',
        'city_name': '来宾',
        'city_code': '202',
        'city_pinyin_code': 'laibin',
      },
      {
        'id': '451400',
        'province_id': '450000',
        'city_name': '崇左',
        'city_code': '144',
        'city_pinyin_code': 'chongzuo',
      },
    ],
  },
  {
    'id': '460000',
    'province_name': '海南省',
    'city_list': [
      {
        'id': '460100',
        'province_id': '460000',
        'city_name': '海口',
        'city_code': '125',
        'city_pinyin_code': 'haikou',
      },
      {
        'id': '460200',
        'province_id': '460000',
        'city_name': '三亚',
        'city_code': '121',
        'city_pinyin_code': 'sanya',
      },
    ],
  },
  {
    'id': '500000',
    'province_name': '重庆市',
    'city_list': [
      {
        'id': '500100',
        'province_id': '500000',
        'city_name': '重庆',
        'city_code': '132',
        'city_pinyin_code': 'chongqing',
      },
    ],
  },
  {
    'id': '510000',
    'province_name': '四川省',
    'city_list': [
      {
        'id': '510100',
        'province_id': '510000',
        'city_name': '成都',
        'city_code': '75',
        'city_pinyin_code': 'chengdou',
      },
      {
        'id': '510300',
        'province_id': '510000',
        'city_name': '自贡',
        'city_code': '78',
        'city_pinyin_code': 'zigong',
      },
      {
        'id': '510400',
        'province_id': '510000',
        'city_name': '攀枝花',
        'city_code': '81',
        'city_pinyin_code': 'panzhihua',
      },
      {
        'id': '510500',
        'province_id': '510000',
        'city_name': '泸州',
        'city_code': '331',
        'city_pinyin_code': 'luzhou',
      },
      {
        'id': '510600',
        'province_id': '510000',
        'city_name': '德阳',
        'city_code': '74',
        'city_pinyin_code': 'deyang',
      },
      {
        'id': '510700',
        'province_id': '510000',
        'city_name': '绵阳',
        'city_code': '240',
        'city_pinyin_code': 'mianyang',
      },
      {
        'id': '510800',
        'province_id': '510000',
        'city_name': '广元',
        'city_code': '329',
        'city_pinyin_code': 'guangyuan',
      },
      {
        'id': '510900',
        'province_id': '510000',
        'city_name': '遂宁',
        'city_code': '330',
        'city_pinyin_code': 'suining',
      },
      {
        'id': '511000',
        'province_id': '510000',
        'city_name': '内江',
        'city_code': '248',
        'city_pinyin_code': 'neijiang',
      },
      {
        'id': '511100',
        'province_id': '510000',
        'city_name': '乐山',
        'city_code': '79',
        'city_pinyin_code': 'leshan',
      },
      {
        'id': '511300',
        'province_id': '510000',
        'city_name': '南充',
        'city_code': '291',
        'city_pinyin_code': 'nanchong',
      },
      {
        'id': '511400',
        'province_id': '510000',
        'city_name': '眉山',
        'city_code': '77',
        'city_pinyin_code': 'meishan',
      },
      {
        'id': '511500',
        'province_id': '510000',
        'city_name': '宜宾',
        'city_code': '186',
        'city_pinyin_code': 'yibin',
      },
      {
        'id': '511600',
        'province_id': '510000',
        'city_name': '广安',
        'city_code': '241',
        'city_pinyin_code': 'guangan',
      },
      {
        'id': '511700',
        'province_id': '510000',
        'city_name': '达州',
        'city_code': '369',
        'city_pinyin_code': 'dazhou',
      },
      {
        'id': '511800',
        'province_id': '510000',
        'city_name': '雅安',
        'city_code': '76',
        'city_pinyin_code': 'yaan',
      },
      {
        'id': '511900',
        'province_id': '510000',
        'city_name': '巴中',
        'city_code': '239',
        'city_pinyin_code': 'bazhong',
      },
      {
        'id': '512000',
        'province_id': '510000',
        'city_name': '资阳',
        'city_code': '242',
        'city_pinyin_code': 'ziyang',
      },
      {
        'id': '513200',
        'province_id': '510000',
        'city_name': '阿坝藏族羌族自治州',
        'city_code': '185',
        'city_pinyin_code': 'abazangzuqiangzuzizhizhou',
      },
      {
        'id': '513300',
        'province_id': '510000',
        'city_name': '甘孜藏族自治州',
        'city_code': '73',
        'city_pinyin_code': 'ganzizangzuzizhizhou',
      },
      {
        'id': '513400',
        'province_id': '510000',
        'city_name': '凉山彝族自治州',
        'city_code': '80',
        'city_pinyin_code': 'liangshanyizuzizhizhou',
      },
    ],
  },
  {
    'id': '520000',
    'province_name': '贵州省',
    'city_list': [
      {
        'id': '520100',
        'province_id': '520000',
        'city_name': '贵阳',
        'city_code': '146',
        'city_pinyin_code': 'guiyang',
      },
      {
        'id': '520200',
        'province_id': '520000',
        'city_name': '六盘水',
        'city_code': '147',
        'city_pinyin_code': 'liupanshui',
      },
      {
        'id': '520300',
        'province_id': '520000',
        'city_name': '遵义',
        'city_code': '262',
        'city_pinyin_code': 'zunyi',
      },
      {
        'id': '520400',
        'province_id': '520000',
        'city_name': '安顺',
        'city_code': '263',
        'city_pinyin_code': 'anshun',
      },
      {
        'id': '522200',
        'province_id': '520000',
        'city_name': '铜仁地区',
        'city_code': '205',
        'city_pinyin_code': 'tongrendiqu',
      },
      {
        'id': '522300',
        'province_id': '520000',
        'city_name': '黔西南布依族苗族自治州',
        'city_code': '343',
        'city_pinyin_code': 'qianxinanbuyizumiaozuzizhizhou',
      },
      {
        'id': '522400',
        'province_id': '520000',
        'city_name': '毕节地区',
        'city_code': '206',
        'city_pinyin_code': 'bijiediqu',
      },
      {
        'id': '522600',
        'province_id': '520000',
        'city_name': '黔东南苗族侗族自治州',
        'city_code': '342',
        'city_pinyin_code': 'qiandongnanmiaozudongzuzizhizhou',
      },
      {
        'id': '522700',
        'province_id': '520000',
        'city_name': '黔南布依族苗族自治州',
        'city_code': '306',
        'city_pinyin_code': 'qiannanbuyizumiaozuzizhizhou',
      },
    ],
  },
  {
    'id': '530000',
    'province_name': '云南省',
    'city_list': [
      {
        'id': '530100',
        'province_id': '530000',
        'city_name': '昆明',
        'city_code': '104',
        'city_pinyin_code': 'kunming',
      },
      {
        'id': '530300',
        'province_id': '530000',
        'city_name': '曲靖',
        'city_code': '249',
        'city_pinyin_code': 'qujing',
      },
      {
        'id': '530400',
        'province_id': '530000',
        'city_name': '玉溪',
        'city_code': '106',
        'city_pinyin_code': 'yuxi',
      },
      {
        'id': '530500',
        'province_id': '530000',
        'city_name': '保山',
        'city_code': '112',
        'city_pinyin_code': 'baoshan',
      },
      {
        'id': '530600',
        'province_id': '530000',
        'city_name': '昭通',
        'city_code': '336',
        'city_pinyin_code': 'zhaotong',
      },
      {
        'id': '530700',
        'province_id': '530000',
        'city_name': '丽江',
        'city_code': '114',
        'city_pinyin_code': 'lijiang',
      },
      {
        'id': '530900',
        'province_id': '530000',
        'city_name': '临沧',
        'city_code': '110',
        'city_pinyin_code': 'lincang',
      },
      {
        'id': '532300',
        'province_id': '530000',
        'city_name': '楚雄彝族自治州',
        'city_code': '105',
        'city_pinyin_code': 'chuxiongyizuzizhizhou',
      },
      {
        'id': '532500',
        'province_id': '530000',
        'city_name': '红河哈尼族彝族自治州',
        'city_code': '107',
        'city_pinyin_code': 'honghehanizuyizuzizhizhou',
      },
      {
        'id': '532600',
        'province_id': '530000',
        'city_name': '文山壮族苗族自治州',
        'city_code': '177',
        'city_pinyin_code': 'wenshanzhuangzumiaozuzizhizhou',
      },
      {
        'id': '532800',
        'province_id': '530000',
        'city_name': '西双版纳傣族自治州',
        'city_code': '109',
        'city_pinyin_code': 'xishuangbannadaizuzizhizhou',
      },
      {
        'id': '532900',
        'province_id': '530000',
        'city_name': '大理白族自治州',
        'city_code': '111',
        'city_pinyin_code': 'dalibaizuzizhizhou',
      },
      {
        'id': '533100',
        'province_id': '530000',
        'city_name': '德宏傣族景颇族自治州',
        'city_code': '116',
        'city_pinyin_code': 'dehongdaizujingpozuzizhizhou',
      },
      {
        'id': '533300',
        'province_id': '530000',
        'city_name': '怒江傈僳族自治州',
        'city_code': '113',
        'city_pinyin_code': 'nujianglisuzuzizhizhou',
      },
      {
        'id': '533400',
        'province_id': '530000',
        'city_name': '迪庆藏族自治州',
        'city_code': '115',
        'city_pinyin_code': 'diqingzangzuzizhizhou',
      },
    ],
  },
  {
    'id': '540000',
    'province_name': '西藏自治区',
    'city_list': [
      {
        'id': '540100',
        'province_id': '540000',
        'city_name': '拉萨',
        'city_code': '100',
        'city_pinyin_code': 'lasa',
      },
      {
        'id': '542100',
        'province_id': '540000',
        'city_name': '昌都地区',
        'city_code': '99',
        'city_pinyin_code': 'changdoudiqu',
      },
      {
        'id': '542200',
        'province_id': '540000',
        'city_name': '山南地区',
        'city_code': '97',
        'city_pinyin_code': 'shannandiqu',
      },
      {
        'id': '542300',
        'province_id': '540000',
        'city_name': '日喀则地区',
        'city_code': '102',
        'city_pinyin_code': 'rikazediqu',
      },
      {
        'id': '542400',
        'province_id': '540000',
        'city_name': '那曲地区',
        'city_code': '101',
        'city_pinyin_code': 'naqudiqu',
      },
      {
        'id': '542500',
        'province_id': '540000',
        'city_name': '阿里地区',
        'city_code': '103',
        'city_pinyin_code': 'alidiqu',
      },
      {
        'id': '542600',
        'province_id': '540000',
        'city_name': '林芝地区',
        'city_code': '98',
        'city_pinyin_code': 'linzhidiqu',
      },
    ],
  },
  {
    'id': '610000',
    'province_name': '陕西省',
    'city_list': [
      {
        'id': '610100',
        'province_id': '610000',
        'city_name': '西安',
        'city_code': '233',
        'city_pinyin_code': 'xian',
      },
      {
        'id': '610200',
        'province_id': '610000',
        'city_name': '铜川',
        'city_code': '232',
        'city_pinyin_code': 'tongchuan',
      },
      {
        'id': '610300',
        'province_id': '610000',
        'city_name': '宝鸡',
        'city_code': '171',
        'city_pinyin_code': 'baoji',
      },
      {
        'id': '610400',
        'province_id': '610000',
        'city_name': '咸阳',
        'city_code': '323',
        'city_pinyin_code': 'xianyang',
      },
      {
        'id': '610500',
        'province_id': '610000',
        'city_name': '渭南',
        'city_code': '170',
        'city_pinyin_code': 'weinan',
      },
      {
        'id': '610600',
        'province_id': '610000',
        'city_name': '延安',
        'city_code': '284',
        'city_pinyin_code': 'yanan',
      },
      {
        'id': '610700',
        'province_id': '610000',
        'city_name': '汉中',
        'city_code': '352',
        'city_pinyin_code': 'hanzhong',
      },
      {
        'id': '610800',
        'province_id': '610000',
        'city_name': '榆林',
        'city_code': '231',
        'city_pinyin_code': 'yulin',
      },
      {
        'id': '610900',
        'province_id': '610000',
        'city_name': '安康',
        'city_code': '324',
        'city_pinyin_code': 'ankang',
      },
      {
        'id': '611000',
        'province_id': '610000',
        'city_name': '商洛',
        'city_code': '285',
        'city_pinyin_code': 'shangluo',
      },
    ],
  },
  {
    'id': '620000',
    'province_name': '甘肃省',
    'city_list': [
      {
        'id': '620100',
        'province_id': '620000',
        'city_name': '兰州',
        'city_code': '36',
        'city_pinyin_code': 'lanzhou',
      },
      {
        'id': '620200',
        'province_id': '620000',
        'city_name': '嘉峪关',
        'city_code': '33',
        'city_pinyin_code': 'jiayuguan',
      },
      {
        'id': '620300',
        'province_id': '620000',
        'city_name': '金昌',
        'city_code': '34',
        'city_pinyin_code': 'jinchang',
      },
      {
        'id': '620400',
        'province_id': '620000',
        'city_name': '白银',
        'city_code': '35',
        'city_pinyin_code': 'baiyin',
      },
      {
        'id': '620500',
        'province_id': '620000',
        'city_name': '天水',
        'city_code': '196',
        'city_pinyin_code': 'tianshui',
      },
      {
        'id': '620600',
        'province_id': '620000',
        'city_name': '武威',
        'city_code': '118',
        'city_pinyin_code': 'wuwei',
      },
      {
        'id': '620700',
        'province_id': '620000',
        'city_name': '张掖',
        'city_code': '117',
        'city_pinyin_code': 'zhangye',
      },
      {
        'id': '620800',
        'province_id': '620000',
        'city_name': '平凉',
        'city_code': '359',
        'city_pinyin_code': 'pingliang',
      },
      {
        'id': '620900',
        'province_id': '620000',
        'city_name': '酒泉',
        'city_code': '37',
        'city_pinyin_code': 'jiuquan',
      },
      {
        'id': '621000',
        'province_id': '620000',
        'city_name': '庆阳',
        'city_code': '135',
        'city_pinyin_code': 'qingyang',
      },
      {
        'id': '621100',
        'province_id': '620000',
        'city_name': '定西',
        'city_code': '136',
        'city_pinyin_code': 'dingxi',
      },
      {
        'id': '621200',
        'province_id': '620000',
        'city_name': '陇南',
        'city_code': '256',
        'city_pinyin_code': 'longnan',
      },
      {
        'id': '622900',
        'province_id': '620000',
        'city_name': '临夏回族自治州',
        'city_code': '182',
        'city_pinyin_code': 'linxiahuizuzizhizhou',
      },
      {
        'id': '623000',
        'province_id': '620000',
        'city_name': '甘南藏族自治州',
        'city_code': '247',
        'city_pinyin_code': 'gannanzangzuzizhizhou',
      },
    ],
  },
  {
    'id': '630000',
    'province_name': '青海省',
    'city_list': [
      {
        'id': '630100',
        'province_id': '630000',
        'city_name': '西宁',
        'city_code': '66',
        'city_pinyin_code': 'xining',
      },
      {
        'id': '632100',
        'province_id': '630000',
        'city_name': '海东地区',
        'city_code': '69',
        'city_pinyin_code': 'haidongdiqu',
      },
      {
        'id': '632200',
        'province_id': '630000',
        'city_name': '海北藏族自治州',
        'city_code': '67',
        'city_pinyin_code': 'haibeizangzuzizhizhou',
      },
      {
        'id': '632300',
        'province_id': '630000',
        'city_name': '黄南藏族自治州',
        'city_code': '70',
        'city_pinyin_code': 'huangnanzangzuzizhizhou',
      },
      {
        'id': '632500',
        'province_id': '630000',
        'city_name': '海南藏族自治州',
        'city_code': '68',
        'city_pinyin_code': 'hainanzangzuzizhizhou',
      },
      {
        'id': '632600',
        'province_id': '630000',
        'city_name': '果洛藏族自治州',
        'city_code': '72',
        'city_pinyin_code': 'guoluozangzuzizhizhou',
      },
      {
        'id': '632700',
        'province_id': '630000',
        'city_name': '玉树藏族自治州',
        'city_code': '71',
        'city_pinyin_code': 'yushuzangzuzizhizhou',
      },
      {
        'id': '632800',
        'province_id': '630000',
        'city_name': '海西蒙古族藏族自治州',
        'city_code': '65',
        'city_pinyin_code': 'haiximengguzuzangzuzizhizhou',
      },
    ],
  },
  {
    'id': '640000',
    'province_name': '宁夏回族自治区',
    'city_list': [
      {
        'id': '640100',
        'province_id': '640000',
        'city_name': '银川',
        'city_code': '360',
        'city_pinyin_code': 'yinchuan',
      },
      {
        'id': '640200',
        'province_id': '640000',
        'city_name': '石嘴山',
        'city_code': '335',
        'city_pinyin_code': 'shizuishan',
      },
      {
        'id': '640300',
        'province_id': '640000',
        'city_name': '吴忠',
        'city_code': '322',
        'city_pinyin_code': 'wuzhong',
      },
      {
        'id': '640400',
        'province_id': '640000',
        'city_name': '固原',
        'city_code': '246',
        'city_pinyin_code': 'guyuan',
      },
      {
        'id': '640500',
        'province_id': '640000',
        'city_name': '中卫',
        'city_code': '181',
        'city_pinyin_code': 'zhongwei',
      },
    ],
  },
  {
    'id': '650000',
    'province_name': '新疆维吾尔自治区',
    'city_list': [
      {
        'id': '650100',
        'province_id': '650000',
        'city_name': '乌鲁木齐',
        'city_code': '92',
        'city_pinyin_code': 'wulumuqi',
      },
      {
        'id': '650200',
        'province_id': '650000',
        'city_name': '克拉玛依',
        'city_code': '95',
        'city_pinyin_code': 'kelamayi',
      },
      {
        'id': '652100',
        'province_id': '650000',
        'city_name': '吐鲁番地区',
        'city_code': '89',
        'city_pinyin_code': 'tulufandiqu',
      },
      {
        'id': '652200',
        'province_id': '650000',
        'city_name': '哈密地区',
        'city_code': '91',
        'city_pinyin_code': 'hamidiqu',
      },
      {
        'id': '652300',
        'province_id': '650000',
        'city_name': '昌吉回族自治州',
        'city_code': '93',
        'city_pinyin_code': 'changjihuizuzizhizhou',
      },
      {
        'id': '652700',
        'province_id': '650000',
        'city_name': '博尔塔拉蒙古自治州',
        'city_code': '88',
        'city_pinyin_code': 'boertalamengguzizhizhou',
      },
      {
        'id': '652800',
        'province_id': '650000',
        'city_name': '巴音郭楞蒙古自治州',
        'city_code': '86',
        'city_pinyin_code': 'bayinguolengmengguzizhizhou',
      },
      {
        'id': '652900',
        'province_id': '650000',
        'city_name': '阿克苏地区',
        'city_code': '85',
        'city_pinyin_code': 'akesudiqu',
      },
      {
        'id': '653000',
        'province_id': '650000',
        'city_name': '克孜勒苏柯尔克孜自治州',
        'city_code': '84',
        'city_pinyin_code': 'kezilesukeerkezizizhizhou',
      },
      {
        'id': '653100',
        'province_id': '650000',
        'city_name': '喀什地区',
        'city_code': '83',
        'city_pinyin_code': 'kashendiqu',
      },
      {
        'id': '653200',
        'province_id': '650000',
        'city_name': '和田地区',
        'city_code': '82',
        'city_pinyin_code': 'hetiandiqu',
      },
      {
        'id': '654000',
        'province_id': '650000',
        'city_name': '伊犁哈萨克自治州',
        'city_code': '90',
        'city_pinyin_code': 'yilihasakezizhizhou',
      },
      {
        'id': '654200',
        'province_id': '650000',
        'city_name': '塔城地区',
        'city_code': '94',
        'city_pinyin_code': 'tachengdiqu',
      },
      {
        'id': '654300',
        'province_id': '650000',
        'city_name': '阿勒泰地区',
        'city_code': '96',
        'city_pinyin_code': 'aletaidiqu',
      },
    ],
  },
  {
    'id': '710000',
    'province_name': '台湾省',
    'city_list': [
      {
        'id': '710000',
        'province_id': '710000',
        'city_name': '台湾',
        'city_code': '710000',
        'city_pinyin_code': 'taiwan',
      },
    ],
  },
  {
    'id': '810000',
    'province_name': '香港特别行政区',
    'city_list': [
      {
        'id': '810000',
        'province_id': '810000',
        'city_name': '香港',
        'city_code': '810000',
        'city_pinyin_code': 'xianggang',
      },
    ],
  },
  {
    'id': '820000',
    'province_name': '澳门特别行政区',
    'city_list': [
      {
        'id': '820000',
        'province_id': '820000',
        'city_name': '澳门',
        'city_code': '820000',
        'city_pinyin_code': 'aomen',
      },
    ],
  },
]
